GitHub Actions Workflow debug.

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -38,18 +38,33 @@ jobs:
             #   timeout-minutes: 5
             #   shell: bash
 
-            - name: Check https://ftppipelinev1backendphplaravel8v1poc1.syncsystem.com.br/system/setup/
-              run: |
-                status=$(curl --write-out '%{http_code}' --silent --output /dev/null https://ftppipelinev1backendphplaravel8v1poc1.syncsystem.com.br/system/setup/)
-                if [[ "$status" -ne 200 ]] ; then
-                    echo "Site not reachable"
-                    exit 1
-                fi
+            - name: Deploy Follow-up Actions (backend)
+            #   run: |
+            #     status=$(curl --write-out '%{http_code}' --silent --output /dev/null https://ftppipelinev1backendphplaravel8v1poc1.syncsystem.com.br/system/setup/)
+            #     if [[ "$status" -ne 200 ]] ; then
+            #         echo "Site not reachable"
+            #         exit 1
+            #     fi
 
-            - name: Check https://ftppipelinev1multiplatformphplaravel8v1poc1.syncsystem.com.br/system/setup/
               run: |
-                status=$(curl --write-out '%{http_code}' --silent --output /dev/null https://ftppipelinev1multiplatformphplaravel8v1poc1.syncsystem.com.br/system/setup/)
+                response=$(curl --write-out "\n\nStatus Code: %{http_code}" --silent https://${{ secrets.BACKEND_FTP_ADDRESS }}/system/setup/)
+                status=$(echo "$response" | tail -n1 | awk '{print $4}') # Extract status code
                 if [[ "$status" -ne 200 ]] ; then
-                    echo "Site not reachable"
+                    echo "Deploy Follow-up Actions Error - Debug and Check Steps/Log"
                     exit 1
-                fi              
+                else
+                    echo "Deploy Follow-up Actions Successful"
+                    echo "Content: $response"
+                fi                
+
+            - name: Deploy Follow-up Actions (frontend)
+              run: |
+                response=$(curl --write-out "\n\nStatus Code: %{http_code}" --silent https://${{ secrets.FRONTEND_FTP_ADDRESS }}/system/setup/)
+                status=$(echo "$response" | tail -n1 | awk '{print $4}') # Extract status code
+                if [[ "$status" -ne 200 ]] ; then
+                    echo "Deploy Follow-up Actions Error - Debug and Check Steps/Log"
+                    exit 1
+                else
+                    echo "Deploy Follow-up Actions Successful"
+                    echo "Content: $response"
+                fi                
